"use client";
import { useEffect, useState } from "react";
import { readStoredSession } from "../../lib/clientSession";

type Announcement={id:string;title:string;message:string;kind:string;priority:string;published:boolean;created_at:string};
function headers(){const {session,user}=readStoredSession();const h:HeadersInit={"Content-Type":"application/json"};if(session.access_token)h.authorization="Bearer "+session.access_token;if(user.id)h["x-user-id"]=user.id;return h;}
export default function AnnouncementManager(){
 const [items,setItems]=useState<Announcement[]>([]);const [title,setTitle]=useState("");const [message,setMessage]=useState("");const [kind,setKind]=useState("general");const [priority,setPriority]=useState("normal");const [published,setPublished]=useState(true);const [status,setStatus]=useState("");
 const load=async()=>{try{const r=await fetch("/api/announcements?manager=1",{headers:headers(),cache:"no-store"});const p=await r.json();if(p.ok)setItems(p.announcements||[])}catch(e){setStatus("Could not load announcements.")}};
 useEffect(()=>{void load()},[]);
 const create=async()=>{if(!title.trim()||!message.trim()){setStatus("Enter a title and message.");return}setStatus("Publishing…");try{const r=await fetch("/api/announcements",{method:"POST",headers:headers(),body:JSON.stringify({title,message,kind,priority,published})});const p=await r.json();if(!r.ok||!p.ok)throw new Error(p.reason);setTitle("");setMessage("");setStatus("Announcement published successfully.");await load()}catch(e){setStatus(e instanceof Error?e.message:"Publish failed.")}};
 const remove=async(id:string)=>{if(!confirm("Delete this announcement?"))return;const r=await fetch("/api/announcements",{method:"DELETE",headers:headers(),body:JSON.stringify({id})});const p=await r.json();setStatus(p.message||p.reason||"");await load()};
 return <section className="manager-card"><h3>Customer Announcements</h3><p className="manager-subtitle">Publish a large premium notice shown to customers when they open the website.</p><div className="manager-form-grid"><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Welcome to AQE" /></label><label>Type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="welcome">Welcome</option><option value="maintenance">Maintenance</option><option value="upgrade">System upgrade</option><option value="promotion">Promotion</option><option value="general">General</option></select></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><label className="manager-wide">Message<textarea rows={5} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Announcement information..." /></label></div><label className="manager-check"><input type="checkbox" checked={published} onChange={e=>setPublished(e.target.checked)} /> Publish immediately</label><div className="manager-page-actions"><button type="button" onClick={create}>Publish announcement</button><span>{status}</span></div><div className="manager-list-table">{items.map(x=><div className="manager-row" key={x.id}><div><strong>{x.title}</strong><span>{x.kind} · {x.priority} · {x.published?"Published":"Draft"}</span></div><div className="manager-row-actions"><button type="button" className="manager-danger-button" onClick={()=>remove(x.id)}>Delete</button></div></div>)}</div></section>
}
