"use client";
import { useEffect,useState } from "react";
import { readStoredSession } from "../../lib/clientSession";
type Task={id:string;title:string;description:string;task_type:string;reward_qc:number;reward_cash:number;active:boolean};
function headers(){const {session,user}=readStoredSession();const h:HeadersInit={"Content-Type":"application/json"};if(session.access_token)h.authorization="Bearer "+session.access_token;if(user.id)h["x-user-id"]=user.id;return h;}
export default function VipTaskManager(){
 const [items,setItems]=useState<Task[]>([]);const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [rewardQc,setRewardQc]=useState("0");const [rewardCash,setRewardCash]=useState("0");const [status,setStatus]=useState("");
 const load=async()=>{try{const r=await fetch("/api/vip/tasks?manager=1",{headers:headers(),cache:"no-store"});const p=await r.json();if(p.ok)setItems(p.tasks||[])}catch{}};
 useEffect(()=>{void load()},[]);
 const create=async()=>{if(!title.trim()){setStatus("Task title is required.");return}setStatus("Saving…");try{const r=await fetch("/api/vip/tasks",{method:"POST",headers:headers(),body:JSON.stringify({managerAction:"create",title,description,rewardQc:Number(rewardQc)||0,rewardCash:Number(rewardCash)||0})});const p=await r.json();if(!r.ok||!p.ok)throw new Error(p.reason);setTitle("");setDescription("");setRewardQc("0");setRewardCash("0");setStatus("VIP task published.");await load()}catch(e){setStatus(e instanceof Error?e.message:"Save failed.")}};
 const remove=async(id:string)=>{if(!confirm("Delete this VIP task?"))return;await fetch("/api/vip/tasks",{method:"POST",headers:headers(),body:JSON.stringify({managerAction:"delete",id})});await load()};
 return <section className="manager-card"><h3>VIP Tasks Configuration</h3><p className="manager-subtitle">Create tasks that verified VIP members can complete. Configure QC and cash rewards from here.</p><div className="manager-form-grid"><label>Task title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Invite a verified member" /></label><label>QC reward<input type="number" min="0" value={rewardQc} onChange={e=>setRewardQc(e.target.value)} /></label><label>Cash reward (UGX)<input type="number" min="0" value={rewardCash} onChange={e=>setRewardCash(e.target.value)} /></label><label className="manager-wide">Description<textarea rows={4} value={description} onChange={e=>setDescription(e.target.value)} /></label></div><div className="manager-page-actions"><button type="button" onClick={create}>Publish VIP task</button><span>{status}</span></div><div className="manager-list-table">{items.map(x=><div className="manager-row" key={x.id}><div><strong>{x.title}</strong><span>{x.description} · {Number(x.reward_qc||0)} QC · UGX {Number(x.reward_cash||0).toLocaleString()}</span></div><div className="manager-row-actions"><button type="button" className="manager-danger-button" onClick={()=>remove(x.id)}>Delete</button></div></div>)}</div></section>
}
