import { NextResponse } from "next/server";
import { resolveAuthenticatedSession } from "../../../lib/aqe/auth";
import { createServerSupabaseClient } from "../../../lib/supabaseServer";

async function countRows(
  client: NonNullable<ReturnType<typeof createServerSupabaseClient>>,
  table: string,
  column?: string,
  value?: string,
) {
  let query = client.from(table).select("*", { count: "exact", head: true });
  if (column && value) query = query.eq(column, value);
  const result = await query;
  if (result.error) {
    console.error("[AQE dashboard] countRows failed", {
      table,
      column,
      value,
      code: result.error.code,
      message: result.error.message,
      details: result.error.details,
      hint: result.error.hint,
    });
    return 0;
  }
  return result.count ?? 0;
}

export async function GET(request: Request) {
  try {
    const session = await resolveAuthenticatedSession(request);
    const client = createServerSupabaseClient();

    if (!client) {
      return NextResponse.json({
        ok: true,
        source: "demo",
        customer: {
          walletBalance: 0,
          qcBalance: 0,
          tier: "basic",
          bookings: 0,
          earnings: 0,
        },
        manager: {
          users: 0,
          vip: 0,
          media: 0,
          transactions: 0,
          bookings: 0,
          messages: 0,
          products: 0,
          support: 0,
          withdrawals: 0,
        },
      });
    }

    if (!session.authenticated || !session.userId) {
      return NextResponse.json(
        { ok: false, reason: "Authentication required." },
        { status: 401 },
      );
    }

    const profile = await client
      .from("profiles")
      .select("tier")
      .eq("user_id", session.userId)
      .maybeSingle();
    const wallet = await client
      .from("qc_wallet")
      .select("balance")
      .eq("user_id", session.userId)
      .maybeSingle();
    const cashWallet = await client
      .from("cash_wallet")
      .select("available_balance,pending_balance,currency")
      .eq("user_id", session.userId)
      .maybeSingle();

    // Earnings are credits generated by the ecosystem, not money the member
    // deposited into their wallet and not withdrawal refunds.
    const earningLedger = await client
      .from("cash_wallet_ledger")
      .select("amount,currency,reference_type,created_at")
      .eq("user_id", session.userId)
      .eq("direction", "CREDIT")
      .neq("reference_type", "WALLET_DEPOSIT")
      .neq("reference_type", "WITHDRAWAL_REFUND");

    if (earningLedger.error) {
      console.error("[AQE dashboard] earnings query failed", {
        code: earningLedger.error.code,
        message: earningLedger.error.message,
        details: earningLedger.error.details,
        hint: earningLedger.error.hint,
      });
    }

    const earningRows = earningLedger.error ? [] : earningLedger.data ?? [];
    const earningSources = earningRows.reduce<Record<string, number>>(
      (totals, row) => {
        const type = String(row.reference_type || "").toUpperCase();
        const source =
          type.includes("REFERRAL")
            ? "Referral earnings"
            : type.includes("TEAM_LEADER")
              ? "Team leader commissions"
              : type.includes("VIP_CONTENT")
                ? "Creator content earnings"
                : type.includes("SALARY")
                  ? "VIP salary"
                  : type.includes("REWARD") || type.includes("CAMPAIGN") || type.includes("RAFFLE")
                    ? "Rewards & campaigns"
                    : "Other ecosystem earnings";
        totals[source] = (totals[source] || 0) + Number(row.amount || 0);
        return totals;
      },
      {},
    );
    const totalEarnings = earningRows.reduce(
      (sum, row) => sum + Number(row.amount || 0),
      0,
    );
    const customerBookings = await countRows(
      client,
      "bookings",
      "customer_id",
      session.userId,
    );
    const earnings = totalEarnings;

    if (session.role === "manager" || session.role === "admin") {
      const countsResult = await client.rpc("aqe_manager_dashboard_counts");
      if (countsResult.error) {
        console.error("[AQE dashboard] manager counts RPC failed", countsResult.error);
        return NextResponse.json(
          { ok: false, reason: "Manager dashboard counts are temporarily unavailable." },
          { status: 503 },
        );
      }
      const counts = (countsResult.data ?? {}) as Record<string, unknown>;
      const transactionCount = await countRows(client, "transaction_receipts");

      return NextResponse.json({
        ok: true,
        source: "supabase",
        customer: {
          walletBalance: cashWallet.data?.available_balance ?? 0,
          qcBalance: wallet.data?.balance ?? 0,
          tier: profile.data?.tier ?? "basic",
          bookings: customerBookings,
          earnings,
          totalEarnings,
          earningsBySource: earningSources,
          pendingEarnings: cashWallet.data?.pending_balance ?? 0,
          currency: cashWallet.data?.currency ?? "UGX",
        },
        manager: {
          users: Number(counts.users ?? 0),
          vip: Number(counts.vip ?? 0),
          media: Number(counts.media ?? 0),
          transactions: transactionCount,
          bookings: Number(counts.bookings ?? 0),
          messages: Number(counts.messages ?? 0),
          products: Number(counts.products ?? 0),
          support: Number(counts.support ?? 0),
          withdrawals: Number(counts.withdrawals ?? 0),
        },
      });
    }

    return NextResponse.json({
      ok: true,
      source: "supabase",
      customer: {
        walletBalance: cashWallet.data?.available_balance ?? 0,
        qcBalance: wallet.data?.balance ?? 0,
        tier: profile.data?.tier ?? "basic",
        bookings: customerBookings,
        earnings,
        totalEarnings,
        earningsBySource: earningSources,
        pendingEarnings: cashWallet.data?.pending_balance ?? 0,
        currency: cashWallet.data?.currency ?? "UGX",
      },
      manager: null,
    });
  } catch (error) {
    return NextResponse.json(
      {
        ok: false,
        reason:
          error instanceof Error
            ? error.message
            : "Dashboard data unavailable.",
      },
      { status: 500 },
    );
  }
}
